pipeline:
  build:
    image: alpine
    commands:
      - bin/hugo
  publish:
    image: plugins/docker
    repo: registry.nfsmith.ca/website
    registry: registry.nfsmith.ca
    auto_tag: true
    secrets: [docker_username, docker_password]