pipeline:
  build-site:
    image: jojomi/hugo
    commands:
      - hugo
  build-server:
    image: golang
    commands:
      - CGO_ENABLED=0 go build -o server -ldflags '-s' src/main.go
  publish:
    image: plugins/docker
    repo: registry.nfsmith.ca/website
    registry: registry.nfsmith.ca
    auto_tag: true
    secrets: [docker_username, docker_password]